name: CI/CD Productos Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:

  build-deploy-api:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore legacy NuGet packages API
      run: nuget restore ./Productos.API/Productos.API.sln -PackagesDirectory ./Productos.API/packages

    - name: Restore API
      run: dotnet restore ./Productos.API/API/Producto.API.csproj

    - name: Build API
      run: dotnet build ./Productos.API/API/Producto.API.csproj --configuration Release --no-restore

    - name: Publish API
      run: dotnet publish ./Productos.API/API/Producto.API.csproj -c Release -o ./publish/api --no-build

    - name: Deploy API
      uses: azure/webapps-deploy@v3
      with:
        app-name: sc701productos
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        package: ./publish/api

  build-deploy-web:
    runs-on: windows-latest
    needs: build-deploy-api

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Web
      run: dotnet restore ./Productos.Web/Web/Web.csproj

    - name: Build Web
      run: dotnet build ./Productos.Web/Web/Web.csproj --configuration Release --no-restore

    - name: Publish Web
      run: dotnet publish ./Productos.Web/Web/Web.csproj -c Release -o ./publish/web --no-build

    - name: Deploy Web
      uses: azure/webapps-deploy@v3
      with:
        app-name: productosweb
        publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
        package: ./publish/web
